version: "3.9"
services:
  server:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
    depends_on:
      - db
  db:
    ports:
      - 5432:5432
    image: postgres:latest
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
  app:
    build: ./frontend/LuxonisFrontend
    ports:
      - 8080:8080
